# Generated by Django 3.1.7 on 2021-03-29 09:03

import audioApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audioApp', '0003_auto_20210329_1352'),
    ]

    operations = [
        migrations.RenameField(
            model_name='audiobook',
            old_name='Narrator',
            new_name='narrator',
        ),
        migrations.AlterField(
            model_name='podcast',
            name='participants',
            field=models.TextField(blank=True, validators=[audioApp.models.validate_participants]),
        ),
    ]
